version: 0.2

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Starting terraform deployment'
      - echo "[INFO] Current target account number is $ACCOUNT"
      - terraform init -backend-config="bucket=$ACCOUNT-tfstate" -backend-config="key=terraform-state" -backend-config="region=us-east-1"
  build:
    commands:
      - echo "[INFO] Running terraform plan"
      - terraform plan -var "account_id=$ACCOUNT"
      - terraform apply -auto-approve -var "account_id=$ACCOUNT"
  post_build:
    commands:
      - echo "[INFO] Terraform plan ran sucessfully."