name: Lint
on:
  pull_request:
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: hashicorp/setup-terraform@v2
      run: terraform init && terraform validate

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.40.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint on root directory
      run: tflint -f compact

    - name: Run TFLint on auth directory      
      run: tflint modules/Auth -f compact

    - name: Run TFLint on compute directory  
      run: tflint modules/Compute -f compact

    - name: Run TFLint on EventStreams directory  
      run: tflint modules/EventStreams -f compact

    - name: Run TFLint on Global directory  
      run: tflint modules/Global -f compact

    - name: Run TFLint on Network directory  
      run: tflint modules/Network -f compact

    - name: Run TFLint on Storage directory  
      run: tflint modules/Storage -f compact
